### ISSUE TITLE
Run App Issue

### ISSUE THREAD

**Issue by MatthewRamsey** [mimicmobile/flutter-conference-app#2]
When trying to run the app after the initial clone, I get an error for the firebase configuration (screenshot for iOS emulator):

![image](https://user-images.githubusercontent.com/14944537/51639240-05522a80-1f26-11e9-8719-21372fddd9d2.png)

I got a good build using: flutter run -t lib/main_dev.dart

But the app doesn't fully load on the emulator due to the firebase configuration. Any ideas?

**Comment by corcoran** [comment]
I've added a default firebase config that should work -- sorry about that!
